version: '3'
services:

  member:
    image: gwangjang/member
    depends_on:
      - eureka
      - apigateway
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://3.34.93.53:8761/eureka/
    ports:
      - 8083:8083
    networks:
      - msa-network
    build: ./MemberService
networks:
  msa-network:
